"""Add ON DELETE CASCADE to task FKs

Revision ID: 3d5da48206cf
Revises: f52cde1dd4f1
Create Date: 2025-12-07 07:53:08.577951

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5da48206cf'
down_revision: Union[str, Sequence[str], None] = 'f52cde1dd4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
